# Generated by Django 4.2 on 2023-06-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('star', models.IntegerField(max_length=5)),
                ('where', models.TextField(max_length=200)),
                ('time', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='list',
        ),
    ]
